### PR TITLE
Add get to Maybe to retrieve inner value

### PR DESCRIPTION
**Pull request by mgoffan**
Hey @rametta!

I've been using this module and It has been great. I made this PR to add `get` to Maybe to retrieve the encapsulated value. I've been working in a project with Typescript and it became really hard to just have `cata` to retrieve the inner value, and to be forced to have a default for `Nothing`, when we know beforehand that the value inside is not null or undefined. There are a lot of times where I have the following scenario:

```js
const someValue: SomeType = (() => {
    if (someMaybe.isJust()) {
        /// I'd like to get the value here
        return someMaybe.map(someTransform).cata({
            Just: v => v,
            Nothing: () => null
        })
    }
    /// ....more code
})();
```

In this case, `SomeType` can't be null, and it may be a complex type that does not have a safe default.

By the way, I thought about http://hackage.haskell.org/package/base-4.14.0.0/docs/Data-Maybe.html and they sometimes throw instead of returning a safe value. Java Optional does the same thing https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html.

Let me know what you think! Thanks!

### CODE REVIEW

**Comment by rametta** [comment]
Ok, I'm not against this, but please enable .get() to .value(), because the library already has a get() utility function.
Also please remove that .nvmrc file

Once done, I will merge, should be a neat addition to the lib @mgoffan

**Comment by mgoffan** [comment]
Great! I just renamed `get` to `value`, updated the tests and the README.

Thanks and congrats on the library!

**Comment by rametta** [comment]
Merged and deployed version [2.0.3](https://www.npmjs.com/package/pratica/v/2.0.3)

**Comment by rametta** [comment]
Thanks for the contribution @mgoffan !

**Pull request merged**
